config/routes.rb
SeatYourself1::Application.routes.draw do
  
  

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]
  resources :restaurants  do 
    resources :reservations 
  end
  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant

	

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, :through => :reservations

	validates :start_time, :capacity, :name, :street_address, :city, :province, :postal_code, :neighborhood, :cuisine, :dining_style, :website, :email, :phone_no, :description, :presence => true

	def availability? (reservation)
		people = 0
		people = self.reservations.
		where(reserve_time: reservation.reserve_time)
		.sum(:seats)
		(people + reservation.seats) < capacity
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :restaurants, :through => :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant
  
  
  def show
  	@reservations = Reservation.find[params[:id]]
  end

  def new
  	@reservation = Reservation.new
    @restaruant = Restaurant.find_by_id(params[:restaurant])
  end

  def create
  	@reservation = Reservation.new(reservation_params)
    @restaurant = Restaurant.find_by_id(params[:restaurant_id])
  		@reservation.user_id = current_user.id      
  		if @restaurant.availability?(@reservation) && @reservation.save 
  		redirect_to restaurants_path, notice: "Reservation created"
  	  else
  		  redirect_to :show
  	  end
  end

  def destroy
  	@reservation = Reservation.find(params[:id])
  	@reservation.destroy
  end

  def reservation_params
  	params.require(:reservation).permit(:reserve_time, :seats)
  end

  def load_restaurant
  	@restaurant = Restaurant.find_by_id(params[:restaurant])
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
    render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurants_path(@restaurant), notice: "Restaurant has been updated"
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path

  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :street_address, :city, :province, :postal_code, :neighborhood, :cuisine, :price_range, :dining_style, :website, :email, :phone_no, :special_meals, :description, :capacity, :sat_open, :sat_close, :sun_open, :sun_close, :start_time, :end_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to restaurants_path, :notice => "Logged in!"
  	else 
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to restaurants_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to restaurants_path
  	else 
  		render :new
  	end
  end

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :address_line1, :address_line2, :postal_code, :city, :province, :telphone_no)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	

		
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.first_name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <div class= "login"><%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %></div>
      <% end %>
    </div>
        <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

<%= yield %>

</body>
</html>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<% if @restaurant.errors.any? %>
		<div id= "error_explanation">
			<h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved</h2>
				<ul>
					<% @restaurant.errors.full_message.each do |msg| %>
					<li><%= msg %> </li>
					<% end %>
				</ul>
		</div>
	<% end %>

	<div class= "field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>

	<div class= "field">
		<%= f.label :street_address %><br/>
		<%= f.text_field :street_address %>
	</div>

	<div class= "field">
		<%= f.label :city %><br/>
		<%= f.text_field :city %>
	</div>

	<div class= "field">
		<%= f.label :province %><br/>
		<%= f.text_field :province %>
	</div>

	<div class= "field">
		<%= f.label :postal_code %><br/>
		<%= f.text_field :postal_code %>
	</div>

	<div class= "field">
		<%= f.label :neighborhood %><br/>
		<%= f.text_field :neighborhood %>
	</div>

	<div class= "field">
		<%= f.label :cuisine %><br/>
		<%= f.text_field :cuisine %>
	</div>

	<div class= "field">
		<%= f.label :price_range %><br/>
		<%= f.number_field :price_range %>
	</div>

	<div class= "field">
		<%= f.label :dining_style %><br/>
		<%= f.text_field :dining_style %>
	</div>

	<div class= "field">
		<%= f.label :website %><br/>
		<%= f.text_field :website %>
	</div>

	<div class= "field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class= "field">
		<%= f.label :phone_no %><br/>
		<%= f.telephone_field :phone_no %>
	</div>

	<div class= "field">
		<%= f.label :special_meals %><br/>
		<%= f.text_field :special_meals %>
	</div>

	<div class= "field">
		<%= f.label :capacity %><br/>
		<%= f.number_field :capacity %>
	</div>

	<div class= "field">
		<%= f.label :start_time %><br/>
		<%= f.number_field :start_time %>
	</div>

	<div class= "field">
		<%= f.label :end_time %><br/>
		<%= f.number_field :end_time %>
	</div>


	<div class= "field">
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</div>

	 <div class= "action">
	 	<%= f.submit %>
	 </div>
 <% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants</h1>

app/views/restaurants/edit.html.erb
<h1>Index#edit</h1>
<p>Find me in app/views/index/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |r| %>
<div class= restName><%= link_to (r[:name]), restaurant_path(r.id) %></div><br/>
<div class= cusine><%= r.cuisine %>
<%= r.price_range %></div>
<div class= restAdd><%= r.street_address %></div><br/>
<div class= restcity><%= r.city %>, <%= r.province %><%= r.postal_code %></div><br/>
<div class= neighb><%= r.neighborhood %></div>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= render "form" %>

<%=  link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<%=link_to "Back", restaurants_path %>

<h1> <%= @restaurant[:name] %> </h1>
									

<div class= cusine>Cuisine: <%= @restaurant [:cuisine] %><br/>
Price Range: $<%= @restaurant [:price_range] %></div>
<div class= restAdd><%= @restaurant[:street_address] %></div>
<div class= restcity><%= @restaurant [:city] %>, <%= @restaurant [:province] %>  <%= @restaurant [:postal_code] %></div><br/>
<div class= neighb>Neighborhood: <%= @restaurant [:neighborhood] %></div><br/>
<%= @restaurant[:description] %>

	<% if current_user %>
	<h2>Make a reservation</h2>
		<%= form_for [@restaurant, @reservation] do |f| %>
			<% if @reservation.errors.any? %>
				<div id = "error_explanation">
					<h2> <%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

					<ul>
						<% @reservation.errors.full_message do |msg| %>
						 <li> <%= msg %></li>
						 <% end %>
					</ul>
				</div>
			<% end %>

			<div class= "field"><%= f.label :reserve_time %><br/>
			<%= f.datetime_select("reserve_time", order: [:day, :month, :year], discard_minute: true, prompt: { day: 'Select day', month: 'Select month', hour: 'Select hour'}, start_year: 2013, start_hour: @restaurant.start_time, end_hour: @restaurant.end_time ) %><br/></div>
			<div class= "field"><%= f.label :seats %><br/>
			<%= f.number_field( :seats, min: 1) %><br/></div>
			<div class= "action"><%= f.submit %></div>
		<% end %>
	<% else %>
	  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p> 
	<% end %>

app/views/restaurants/update.html.erb
<h1>Index#update</h1>
<p>Find me in app/views/index/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up </h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
   <div class="field">
    <%= f.label :address_line1 %>
    <%= f.text_field :address_line1 %>
  </div>
   <div class="field">
    <%= f.label :address_line2 %>
    <%= f.text_field :address_line2 %>
  </div>
   <div class="field">
   	<%= f.label :city %>
    <%= f.text_field :city %>
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
    <%= f.label :province %>
    <%= f.text_field :province %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>